apiVersion: v1
kind: Service
metadata:
 name: mosquitto
 labels:
  app: mosquitto
spec:
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pv-claim
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
     storage: 20Gi
#  selector:
#    matchLabels:
#      volumetype: local
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mosquitto
 labels:
   app: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:2.0.15
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mosquitto-mqtt
        volumeMounts:
        - name: mosquitto-persistent-storage
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password.txt
          subPath: password.txt
      volumes:
      - name: mosquitto-persistent-storage
        persistentVolumeClaim:
          claimName: mosquitto-pv-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-password
        configMap:
          name: mosquitto-password