apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mqtt
  name: mosquitto-password
  labels:
    app: mosquitto
data:
  password.txt: |
    admin:$6$IHf5yFBHSIwXbEBs$OhEezy1uLHiosFA/xcPOPREEduqKSiYGtRK++KyKA4Yuhk6q87GI9RqCbe3GxZ9XzbWU4zUjGnKy3nPGu37Y3w==