apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
metadata:
  labels:
    app.kubernetes.io/name: controllermanagerconfig
    app.kubernetes.io/instance: controller-manager-configuration
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: controller-tutorial
    app.kubernetes.io/part-of: controller-tutorial
    app.kubernetes.io/managed-by: kustomize
MQTT_BROKER: tcp://192.168.0.70:1883
MQTT_CLIENT_ID: personalIOTController

