---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-personal-iot-frup-org-v1alpha1-poweroutlet
  failurePolicy: Fail
  name: mpoweroutlet.kb.io
  rules:
  - apiGroups:
    - personal-iot.frup.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - poweroutlets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-personal-iot-frup-org-v1alpha1-poweroutlet
  failurePolicy: Fail
  name: vpoweroutlet.kb.io
  rules:
  - apiGroups:
    - personal-iot.frup.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - poweroutlets
  sideEffects: None
