# permissions for end users to view powerstrips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: powerstrip-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller-tutorial
    app.kubernetes.io/part-of: controller-tutorial
    app.kubernetes.io/managed-by: kustomize
  name: powerstrip-viewer-role
rules:
- apiGroups:
  - personal-iot.frup.org
  resources:
  - powerstrips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - personal-iot.frup.org
  resources:
  - powerstrips/status
  verbs:
  - get
