apiVersion: personal-iot.frup.org/v1alpha1
kind: Poweroutlet
metadata:
  labels:
    app.kubernetes.io/name: poweroutlet
    app.kubernetes.io/instance: poweroutlet-sample
    app.kubernetes.io/part-of: controller-tutorial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller-tutorial
  name: poweroutlet-sample
spec:
  # TODO(user): Add fields here
