apiVersion: personal-iot.frup.org/v1alpha1
kind: Powerstrip
metadata:
  labels:
    app.kubernetes.io/name: powerstrip
    app.kubernetes.io/instance: powerstrip-sample
    app.kubernetes.io/part-of: controller-tutorial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller-tutorial
  name: powerstrip-sample
spec:
  # TODO(user): Add fields here
